<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository {

    public function findLast($limit) {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('b', 'a')
                        ->from('AppBundle:Book', 'b')
                        ->innerJoin('b.author', 'a')
                        ->orderBy('b.createdAt', 'DESC')
                        ->setMaxResults($limit)
                        ->getQuery()
                        ->getResult()
        ;
    }

    public function getRandomBooks($bookId){

        $sql = 'SELECT * 
                FROM book_lib.book 
                INNER JOIN book_lib.author
                ON book.author_id = author.id
                WHERE book.id != :notId
                ORDER BY rand() 
                LIMIT 3 ;';

        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->bindParam(':notId', $bookId);
        $stmt->execute();
        return $stmt->fetchAll();

    }

}
